export const THERMO_LEARN_DATA: Record<string, string> = {
  "System": "A quantity of matter or a region in space chosen for study.",
  "Surroundings": "The mass or region outside the system.",
  "Boundary": "The real or imaginary surface that separates the system from its surroundings.",
  "Open system": "A control volume where both mass and energy can cross the boundary.",
  "Closed system": "A control mass where energy can cross the boundary, but mass cannot.",
  "Isolated system": "A system where neither mass nor energy can cross the boundary.",
  "State": "The exact condition of a system as described by its properties.",
  "Process": "Any change that a system undergoes from one equilibrium state to another.",
  "Cycle": "A series of processes that eventually return the system to its initial state.",
  "Intensive properties": "Properties that are independent of the mass of a system, such as temperature, pressure, and density.",
  "Extensive properties": "Properties whose values depend on the size or extent of the system, such as total mass, total volume, and total momentum.",
  "Equilibrium": "A state of balance where there are no unbalanced potentials (or driving forces) within the system.",
  "Quasi-static process": "A process that proceeds in such a manner that the system remains infinitesimally close to an equilibrium state at all times.",
  "Pressure": "A normal force exerted by a fluid per unit area.",
  "Temperature": "A measure of the average kinetic energy of the particles in a substance.",
  "Volume": "The amount of three-dimensional space occupied by a substance.",
  "Specific volume": "The volume per unit mass of a substance, which is the reciprocal of density.",
  "Density": "The mass per unit volume of a substance.",
  "Internal energy": "The sum of all the microscopic forms of energy (sensible, latent, chemical, and nuclear) of a system.",
  "Enthalpy": "A thermodynamic property defined as H = U + PV, representing the total heat content of a system.",
  "Entropy": "A measure of molecular disorder or randomness; also represents the unavailability of a system's thermal energy for conversion into mechanical work.",
  "Gibbs free energy": "A thermodynamic potential that can be used to calculate the maximum of reversible work that may be performed by a thermodynamic system at a constant temperature and pressure.",
  "Helmholtz free energy": "A thermodynamic potential that measures the useful work obtainable from a closed thermodynamic system at a constant temperature and volume.",
  "Specific heats": "The energy required to raise the temperature of a unit mass of a substance by one degree.",
  "Compressibility factor": "A correction factor introduced to account for the deviation of real gases from ideal-gas behavior at a given temperature and pressure.",
  "Energy conservation": "The first law of thermodynamics; energy can be neither created nor destroyed, only changed in form.",
  "Closed-system energy balance": "Q - W = \u0394U (Heat added minus work done equals change in internal energy).",
  "Open-system energy balance": "Accounts for energy transferred by mass flow in addition to heat and work across the control volume boundary.",
  "Steady-flow energy equation": "The energy balance for a control volume where conditions at all points within the CV do not change with time.",
  "Heat": "The form of energy that is transferred between two systems (or a system and its surroundings) by virtue of a temperature difference.",
  "Work": "The energy transfer associated with a force acting through a distance (or moving boundary, shaft, etc.).",
  "Boundary work": "The expansion or compression work in a piston-cylinder device.",
  "Shaft work": "Energy transmission via a rotating shaft.",
  "Electrical work": "Work done by electrons crossing the system boundary.",
  "Kelvin-Planck statement": "It is impossible for any device that operates on a thermodynamic cycle to receive heat from a single thermal reservoir and produce a net amount of work.",
  "Clausius statement": "It is impossible to construct a device that operates in a cycle and produces no other effect than the transfer of heat from a lower-temperature body to a higher-temperature body.",
  "Reversible processes": "A process that can be reversed without leaving any trace on the surroundings.",
  "Irreversible processes": "Processes that involve friction, unrestrained expansion, mixing of two gases, heat transfer across a finite temperature difference, etc.",
  "Entropy generation": "A measure of the irreversibilities present during a process; always positive for irreversible processes and zero for reversible ones.",
  "Carnot cycle": "The most efficient hypothetical cycle consisting of four totally reversible processes: two isothermal and two adiabatic.",
  "Second-law efficiency": "The ratio of the actual thermal efficiency to the maximum possible (reversible) thermal efficiency under the same conditions.",
  "Phase change": "The transition of matter from one state (solid, liquid, gas) to another.",
  "Compressed liquid": "A liquid that is not about to vaporize (also called a subcooled liquid).",
  "Saturated liquid": "A liquid that is about to vaporize.",
  "Saturated vapor": "A vapor that is about to condense.",
  "Wet region": "The state where liquid and vapor phases coexist in equilibrium.",
  "Superheated vapor": "A vapor that is not about to condense (temperature is higher than the saturation temperature at the given pressure).",
  "Critical point": "The point at which the saturated liquid and saturated vapor states are identical.",
  "Triple point": "The conditions under which all three phases of a pure substance coexist in equilibrium.",
  "Quality": "The ratio of the mass of vapor to the total mass of a liquid-vapor mixture.",
  "Maxwell relations": "Equations that relate the partial derivatives of thermodynamic properties based on exact differentials of thermodynamic potentials.",
  "Exact/inexact differentials": "Properties are exact differentials (point functions); heat and work are inexact differentials (path functions).",
  "Fundamental property relations": "Equations combining the first and second laws (e.g., du = Tds - Pdv and dh = Tds + vdP).",
  "Joule-Thomson effect": "The temperature change of a fluid during a throttling (isenthalpic) process.",
  "Clapeyron equation": "Relates the latent heat of phase change to the change in saturation pressure with temperature and the specific volumes of the two phases.",
  "Clausius-Clapeyron equation": "An approximation of the Clapeyron equation used for liquid-vapor and solid-vapor phase changes assuming ideal gas vapor behavior.",
  "Ideal gases": "A gas whose molecules are spaced far apart so that the behavior of a molecule is not influenced by the presence of other molecules (Pv = RT).",
  "Real gases": "Gases that deviate from ideal behavior, particularly at high pressures and low temperatures.",
  "Equations of state": "Any equation that relates the pressure, temperature, and specific volume of a substance.",
  "van der Waals": "An early equation of state that accounts for intermolecular attraction forces and the volume occupied by the molecules themselves.",
  "Peng-Robinson": "A widely used cubic equation of state in chemical engineering for predicting phase behavior of real fluids.",
  "Soave-Redlich-Kwong": "Another major cubic equation of state used for hydrocarbon vapor-liquid equilibrium.",
  "Fugacity concepts": "An effective or \"corrected\" pressure that replaces the true mechanical pressure in accurate chemical equilibrium calculations.",
  "Carnot": "The ideal, theoretical maximum efficiency cycle.",
  "Rankine": "The ideal cycle for vapor power plants consisting of a pump, boiler, turbine, and condenser.",
  "Reheat Rankine": "A modification of the Rankine cycle where steam is extracted from the turbine, reheated, and sent to a lower-pressure turbine to increase efficiency and avoid excess moisture.",
  "Regenerative Rankine": "A modification where steam is bled from the turbine to heat the feedwater, raising the average temperature of heat addition and thus thermal efficiency.",
  "Brayton": "The ideal cycle for gas turbine engines consisting of a compressor, combustion chamber, and turbine.",
  "Intercooled Brayton": "Calculates the net work increase from multi-stage compression with intercooling.",
  "Reheated Brayton": "Calculates the net work increase from multi-stage expansion with reheating.",
  "Regenerative Brayton": "Calculates fuel savings and efficiency improvements by utilizing a regenerator.",
  "Otto": "The ideal cycle for spark-ignition internal combustion engines.",
  "Diesel": "The ideal cycle for compression-ignition internal combustion engines.",
  "Dual cycle": "A cycle that approximates actual internal combustion engines by modeling heat addition as occurring partly at constant volume and partly at constant pressure.",
  "Refrigeration principle": "The transfer of heat from a lower-temperature region to a higher-temperature one, which requires work input.",
  "Vapor-compression refrigeration": "The most common refrigeration cycle involving a compressor, condenser, expansion valve, and evaporator.",
  "Absorption refrigeration": "A refrigeration cycle where the compressor is replaced by an absorber, pump, and generator mechanism (often using ammonia-water or water-lithium bromide).",
  "COP": "Coefficient of Performance; the ratio of useful heating/cooling provided to the work required.",
  "Refrigerant properties": "Must have favorable thermodynamic properties (high heat of vaporization, moderate pressures), chemical stability, and environmental safety.",
  "Throttling": "The isenthalpic expansion of a fluid from high pressure to low pressure through a restriction, causing a temperature drop in liquids/refrigerants.",
  "Compressor": "A device that increases the pressure of a gas or vapor.",
  "Condenser": "A heat exchanger where refrigerant vapor is condensed to a liquid by rejecting heat to the surroundings.",
  "Expansion valve": "A throttling device that drastically drops the pressure and temperature of the refrigerant.",
  "Evaporator": "A heat exchanger where the cold refrigerant absorbs heat from the refrigerated space and vaporizes.",
  "Mole Fraction": "The ratio of the number of moles of a particular component to the total number of moles in a mixture.",
  "Mass Fraction": "The ratio of the mass of a particular component to the total mass of the mixture.",
  "Average Molecular Weight": "The apparent molar mass of a gas mixture, calculated as the sum of the mole-fraction-weighted molar masses of its components.",
  "Partial Pressure": "The pressure that a component gas would exert if it existed alone at the mixture temperature and volume (Dalton's Law).",
  "Partial Molar Properties": "The contribution (per mole) that a component makes to the total property of a mixture.",
  "Mixture Enthalpy": "The total enthalpy of a mixture, typically the mass- or mole-weighted sum of the pure component enthalpies (for ideal mixtures).",
  "Carnot Cycle Analyzer": "Calculates maximum theoretical thermal efficiency based solely on absolute source and sink temperatures.",
  "Rankine Cycle Analyzer": "Calculates the performance of a standard vapor power plant including pump work, heat added, turbine work, and efficiency.",
  "Reheat Rankine Cycle": "Analyzes the effects of expanding steam in multiple stages with reheating in between.",
  "Regenerative Rankine Cycle": "Analyzes the cycle performance when using open or closed feedwater heaters.",
  "Brayton Cycle": "Analyzes gas turbine performance based on pressure ratio and component efficiencies.",
  "Otto Cycle": "Calculates engine performance and efficiency as a function of the compression ratio.",
  "Diesel Cycle": "Calculates engine performance as a function of the compression ratio and cutoff ratio.",
  "Dual Cycle": "Calculates performance combining both constant volume and constant pressure heat addition.",
  "Refrigeration COP": "Evaluates the performance of a cooling system (Cooling Effect / Work Input).",
  "Heat Pump COP": "Evaluates the performance of a heating system (Heating Effect / Work Input). COP_HP = COP_R + 1.",
  "Vapor Compression Cycle Analyzer": "Calculates state points, mass flow rate, compressor work, and cooling capacity for a real refrigerant.",
  "Refrigeration Capacity": "The rate at which heat is removed from the refrigerated space (often expressed in kW or Tons).",
  "Ton of Refrigeration": "The capacity to freeze 1 short ton of liquid water at 0\u00b0C into ice in 24 hours (1 TR = 3.5168 kW).",
  "Compressor Performance": "Analyzes the isentropic efficiency, volumetric efficiency, and power consumption of a compressor.",
  "Stoichiometric Air Requirement": "The exact amount of theoretical air needed for complete combustion of a fuel.",
  "Excess Air": "The extra air supplied beyond the stoichiometric requirement to ensure complete combustion.",
  "Air-Fuel Ratio": "The ratio of the mass (or moles) of air to the mass (or moles) of fuel in a combustion process.",
  "Equivalence Ratio": "The ratio of the actual fuel-to-air ratio to the stoichiometric fuel-to-air ratio.",
  "Combustion Product Calculation": "Determining the composition of exhaust gases using species conservation and equilibrium relations.",
  "Heating Value": "The amount of heat released when a fuel is burned completely and the products are returned to the initial temperature (HHV vs LHV).",
  "Gibbs Free Energy": "A potential indicating spontaneity; \u0394G < 0 means a process is spontaneous at constant T and P.",
  "Helmholtz Free Energy": "A potential indicating maximum useful work obtainable at constant T and V.",
  "Chemical Potential": "The change in Gibbs free energy with respect to a change in the number of moles of a given component.",
  "Equilibrium Constant from \u0394G\u00b0": "K = exp(-\u0394G\u00b0 / RT), relating the standard Gibbs free energy of reaction to the equilibrium composition.",
  "Reaction Gibbs Energy": "The instantaneous change in Gibbs free energy driving a reaction towards equilibrium.",
  "Equilibrium Constant": "A ratio of the activities of products to reactants at equilibrium.",
  "van't Hoff Equation": "Relates the change in the equilibrium constant with temperature to the standard enthalpy of reaction.",
  "Reaction Enthalpy": "The heat absorbed or released during a chemical reaction at constant pressure.",
  "Reaction Entropy": "The change in entropy accompanying a chemical reaction.",
  "Raoult's Law": "Relates the vapor pressure of components in an ideal mixture to their mole fractions in the liquid and vapor phases (y_i P = x_i P_i^sat).",
  "Bubble Point Pressure": "The pressure at which the first bubble of vapor forms in a liquid mixture at a given temperature.",
  "Dew Point Pressure": "The pressure at which the first drop of liquid forms in a vapor mixture at a given temperature.",
  "Bubble Point Temperature": "The temperature at which a liquid mixture begins to boil at a given pressure.",
  "Dew Point Temperature": "The temperature at which a vapor mixture begins to condense at a given pressure.",
  "Relative Volatility": "A measure comparing the vapor pressures of the components in a liquid mixture; essential for distillation.",
  "K-value Calculator": "Determines the vapor-liquid equilibrium ratio (K_i = y_i / x_i) for a component.",
  "VLE Flash Calculation": "Determines the vapor fraction and the compositions of liquid and vapor phases resulting from flashing a feed at a specified T and P."
};
